Update `README`
spine-examples/Hello-ProtoData pull request #11
Opened 2024-04-21 16:23 UTC by Oleg-Melnik

2024-04-26 12:30 UTC, armiol commented
@Oleg-Melnik please also have a description for this PR.

2024-04-26 12:38 UTC, Oleg-Melnik commented
> @Oleg-Melnik please also have a description for this PR.

@armiol Done.

2024-04-26 12:45 UTC, armiol requested changes
@Oleg-Melnik please see my comments.

2024-04-26 12:45 UTC, armiol commented on README.md
> +message-level options, field-level options, etc. The complete list of
This is not a list of options. This is rather a list of available option types.

As anyone is able to come up with their own options, it is technically impossible to provide a link to a "complete list of available options".

2024-04-26 12:45 UTC, armiol commented on README.md
> +Protobuf also allows to define and use [custom options](https://protobuf.dev/programming-guides/proto2/#customoptions).
This link points at proto2 guide.

2024-04-26 12:45 UTC, armiol commented on README.md
> +a number of [options](https://protobuf.dev/programming-guides/proto3/#options).
Here and below, let's use a footnote-style links, instead of inline links.

2024-04-26 12:45 UTC, armiol commented on README.md
> +[gh-actions]: https://github.com/spine-examples/Hello-ProtoData/actions
Please move these footnote links to the bottom of the page.

2024-04-26 12:45 UTC, armiol commented on README.md
> +with additional semantic elements and reflect its meaning in the generated code.
"their meaning"

2024-04-26 12:45 UTC, armiol commented on README.md
> +For example, let's define a board for TicTacToe game:
["Tic-tac-toe"](https://en.wikipedia.org/wiki/Tic-tac-toe).

2024-04-26 12:45 UTC, armiol commented on README.md
> +1. Mark some fields as `required` to admit that this is important
"Mark some fields as `required` to state the absolute necessity to fill them with real values."

2024-04-26 12:45 UTC, armiol commented on README.md
> +3. Add some validation rules that verify the size of the `cell` collection.
"Add some validation rules that verify the size of the `cell` collection. Indeed, a tic-tac-toe board should be square, and hence have an appropriate number of cells, being the size of the side squared."

2024-04-26 12:45 UTC, armiol commented on README.md
> +We can easily solve the points 1 and 2 as ProtoData provides options
It's not ProtoData who provides this capability. It's Spine.

2024-04-26 12:45 UTC, armiol commented on README.md
> +  // Board cells. It is expected to have "side_size * side_size" cells.
Right now it is still just `required`. Let's rephrase:

```protobuf
// Board cells. The collection must not be empty.
```

2024-04-26 12:45 UTC, armiol commented on README.md
> +and use ProtoData API to generate the required validation code.
In this text, a fact of generating any code is omitted (like it's a given, but it's not). Let's say somewhere above, that the code generated by default from Protobuf may be augmented with more custom logic to check the instances of Proto messages for validness, at runtime.

2024-04-26 12:45 UTC, armiol commented on README.md
> +// A board for TicTacToe game.
```
A board for Tic-tac-toe` game.
```

2024-04-26 12:45 UTC, armiol commented on README.md
> +### Build Instruction
"### Building locally"

And we don't follow any title capitalization anymore. That's something considered obsolete, as of (relatively) new Material guidelines. [Sentence case](https://m3.material.io/foundations/content-design/style-guide/ux-writing-best-practices#fc5c2a78-f4bf-4d42-bdac-42ff80391129) is a designed approach.

Please review other headers for that, as well.

2024-04-29 09:05 UTC, armiol approved these changes

2024-04-29 09:07 UTC, merged